init solution
litentry/worker pull request #48
Opened 2021-12-28 16:07 UTC by suinuj

2022-01-10 07:46 UTC, haerdib commented on app-libs/stf/src/stf_litentry_sgx.rs
> +		let litentry_network_type: NetworkType = match network_type {
Why are these conversions necessary?

2022-01-10 07:46 UTC, haerdib commented on enclave-runtime/src/tests.rs
> +	Stf::execute(&mut state, signed_call, &mut dummy_vec).unwrap();
In case you're also introducing a Getter to get the state, it might be worth to update the tests to also check if the state has been updated as expected (by getting the state with the getter)

2022-01-10 07:57 UTC, suinuj commented on app-libs/stf/src/stf_litentry_sgx.rs
> +		let litentry_network_type: NetworkType = match network_type {
One is defined in the worker, another type is defined in the pallet of sgx runtime.

2022-01-10 08:00 UTC, suinuj commented on enclave-runtime/src/tests.rs
> +	Stf::execute(&mut state, signed_call, &mut dummy_vec).unwrap();
As I remembered, the updated state doesn't work in the unit test. We found the issue when we implemented the unit test for test_call_link_eth

2022-01-10 08:10 UTC, haerdib commented on enclave-runtime/src/tests.rs
> +	Stf::execute(&mut state, signed_call, &mut dummy_vec).unwrap();
Yes, there was a problem. But as far as I understand, the state update should work, also in the tests

(like here: https://github.com/litentry/worker/blob/litentry/enclave-runtime/src/tests.rs#L473-L477)

But ofc, you can also leave it like that.

2022-01-10 08:20 UTC, haerdib commented on app-libs/stf/src/stf_litentry_sgx.rs
> +		let litentry_network_type: NetworkType = match network_type {
Ah, I see. But I think it should be possible to directly import the pallet types into the worker, so you do not need to define the types twice. 

We're doing this here with sgx-externalities: https://github.com/integritee-network/worker/blob/master/app-libs/stf/Cargo.toml#L40
You could do the same with the litentry sgx pallet.

2022-01-10 13:47 UTC, h4n0 requested changes

2022-01-10 13:47 UTC, h4n0 commented on litentry-primitives/src/lib.rs
> +pub mod sub {
I prefer to have a more understandable name, and sub can be very vague.

2022-01-10 13:47 UTC, h4n0 commented on app-libs/stf/src/cli.rs
> +							.help("The index of the linked Ethereum address"),
ethereum? Better specify the range of index here.

2022-01-10 13:47 UTC, h4n0 commented on app-libs/stf/src/cli.rs
> +							.help("Network type relayer chain or relayer chain with parachain id, could be Kusama, Polkadot, Kusama2000, Polkadot2000"),
What are Kusama2000, Polkadot2000?

2022-01-10 13:49 UTC, h4n0 commented
Could you have a look of the clippy issue as well? https://github.com/litentry/worker/runs/4724532007?check_suite_focus=true

2022-01-11 01:10 UTC, suinuj commented on app-libs/stf/src/cli.rs
> +							.help("Network type relayer chain or relayer chain with parachain id, could be Kusama, Polkadot, Kusama2000, Polkadot2000"),
relayer chain with parachain id, as explained.

2022-01-11 01:20 UTC, suinuj commented on app-libs/stf/src/cli.rs
> +							.help("The index of the linked Ethereum address"),
It should be the substrate. For index, according to the extrinsic interface in pallet, it can accept any u32 value.

2022-01-11 01:21 UTC, suinuj commented on litentry-primitives/src/lib.rs
> +pub mod sub {
it is vague, just didn't find out a good name. have considered the substrate, polkadot.

2022-01-11 01:34 UTC, suinuj commented on enclave-runtime/src/tests.rs
> +	Stf::execute(&mut state, signed_call, &mut dummy_vec).unwrap();
will try it

2022-01-11 07:57 UTC, suinuj commented on litentry-primitives/src/lib.rs
> +pub mod sub {
removed after we can import types from pallet directly.

2022-01-11 08:13 UTC, h4n0 commented on litentry-primitives/src/lib.rs
> +pub mod sub {
Yeah both are better than sub IMHO. 
I recommend using substrate than sub, to avoid misunderstanding of others.

2022-01-12 07:18 UTC, suinuj commented on enclave-runtime/src/tests.rs
> +	Stf::execute(&mut state, signed_call, &mut dummy_vec).unwrap();
the state update doesn't work, I will use https://github.com/litentry/worker/issues/36 to track it.

2022-01-12 13:51 UTC, haerdib approved these changes
LGTM

2022-01-12 13:51 UTC, haerdib commented on litentry-primitives/src/lib.rs
> +// pub mod sub {
Is this left here on purpose?

2022-01-12 14:24 UTC, suinuj commented on litentry-primitives/src/lib.rs
> +// pub mod sub {
will remove it.

2022-01-13 09:37 UTC, h4n0 approved these changes

2022-01-13 09:44 UTC, merged