Sync the codebase to `integritee-network/worker:master` 5fb794f
litentry/worker pull request #66
Opened 2022-04-22 10:18 UTC by Kailai-Wang

resovles #62 and #64 

This PR:
- syncs the underlying codebase to `integritee-network/worker:master` [5fb794f](https://github.com/integritee-network/worker/commit/5fb794f519cf03b967fa84b47daae12b2b03f1a3)
- uses upstream integritee-node (as the functionalities in our litentry/integritee-node are not used for now)
- patching instead of modifying `integritee-network/sgx-runtime` everywhere
- fixes all clippy and CI issues

2022-04-26 15:37 UTC, h4n0 requested changes

2022-04-27 06:15 UTC, haerdib commented on app-libs/stf/Cargo.toml
> +sc-keystore = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master", optional = true }
It is not possible to unify them, as substrate itself has not yet updated all of its versions: https://github.com/paritytech/substrate/blob/master/client/keystore/Cargo.toml#L3

But we're switching to use polkadot-vx.x.x branches anyway soon, because substrate updates often broke our build, see  : https://github.com/integritee-network/worker/issues/694

2022-04-27 07:44 UTC, Kailai-Wang commented on app-libs/stf/Cargo.toml
> +sc-keystore = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master", optional = true }
> It is not possible to unify them, as substrate itself has not yet updated all of its versions: https://github.com/paritytech/substrate/blob/master/client/keystore/Cargo.toml#L3
> 
> But we're switching to use polkadot-vx.x.x branches anyway soon, because substrate updates often broke our build, see : [integritee-network#694](https://github.com/integritee-network/worker/issues/694)

That would be great, thanks.
I haven't changed it on my own so that I could fast-forward upstream changes later and avoid manually resolving the conflicts

2022-04-27 08:01 UTC, h4n0 commented on .github/workflows/build_and_test.yml
> +          repo: integritee-network/integritee-node
I would agree with the 1 and 3 points. However, I think switching to the parachain node is a long way to go. There are still 2 points that we need to take into consideration:

1. Integrating teerex into our parachain requires effort and time to test, especially Polkadot/substrate dependencies, which could be an obstacle to keep us from integrating teerex in a short time.
2. The CI from upstream is still not adapting parachain with tests, which means we may spend extra time to setup an env for that. 

I would say these 2 points are kinda unknown to us and they could be blockers for our development and testing.

2022-04-27 09:43 UTC, Kailai-Wang commented on .github/workflows/build_and_test.yml
> +          repo: integritee-network/integritee-node
It's too much work to update 3 Repos simultaneously (and keep them synced in the future), especially when it will get replaced anyway later -- or to put it in another way, I do think the integration of our parachain should happen before or at least not later than the subsequent development 😂 

What's your preference here @suinuj ?

2022-04-27 11:24 UTC, h4n0 commented on .github/workflows/build_and_test.yml
> +          repo: integritee-network/integritee-node
Alright, let's keep that in mind. Thanks Kai.

2022-04-27 11:24 UTC, h4n0 approved these changes

2022-04-27 11:38 UTC, merged